name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - run: docker run --rm -v ${PWD}:/app jones2748/docker-testcl:latest jtcl /app/test_polaris_irule.tcl
